# Generated by Django 5.2.7 on 2025-10-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ethinic_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
