# Generated by Django 5.1.3 on 2025-11-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctor', '0004_delete_schedule'),
        ('patients', '0004_remove_patient_address_remove_patient_birthday_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'date'], name='appointment_doctor__e7d63f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'date', 'time'], name='appointment_doctor__111942_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('status', 'confirmed'), _connector='OR'), fields=('doctor', 'date', 'time'), name='unique_doctor_date_time_when_active'),
        ),
    ]
