# Generated by Django 5.2.7 on 2025-11-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_created_at_doctor_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
