# Generated by Django 5.2.7 on 2025-10-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_cccd_patient_ethinic_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cccd',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ethinic_group',
        ),
    ]
